# Generated by Django 4.1.3 on 2022-11-30 23:16

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3ece4721-307d-49e8-97af-21bd77e4fcee'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('symbol', models.CharField(max_length=255, null=True)),
                ('logo', models.ImageField(default='no-image.png', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b029c15f-e52f-4ff6-afb9-62a2389a00d9'), editable=False, primary_key=True, serialize=False)),
                ('asset_to_stake', models.CharField(max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=models.CharField(max_length=255, null=True))),
                ('asset_image', models.ImageField(default='no-image.png', null=True, upload_to='')),
                ('asset_to_win', models.CharField(max_length=255, null=True)),
                ('apy', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('contract_address', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chains', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stake.chain')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
