# Generated by Django 4.1.3 on 2022-12-02 21:43

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stake',
            old_name='chains',
            new_name='chain',
        ),
        migrations.AlterField(
            model_name='chain',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3ff40386-9f72-4264-97c3-bc7d7c84d211'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stake',
            name='apy',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stake',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85615ad2-0903-43c0-a1a5-44983cf6d4b3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stake',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='asset_to_stake'),
        ),
    ]
