# Generated by Django 4.1.3 on 2022-12-02 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0002_rename_chains_stake_chain_alter_chain_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='id',
            field=models.UUIDField(default=uuid.UUID('583d22b0-8dd0-4188-8b56-1c7f37946868'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stake',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stake',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d217c8e7-819f-499f-bebd-b2b0039ff218'), editable=False, primary_key=True, serialize=False),
        ),
    ]
